//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoComponente.ServiceReferenceUsers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsers.IUsers")]
    public interface IUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/getUsers", ReplyAction="http://tempuri.org/IUsers/getUsersResponse")]
        GrupoComponente.Servicio.Models.ViewModels.UsersIndexViewModel[] getUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/getUsers", ReplyAction="http://tempuri.org/IUsers/getUsersResponse")]
        System.Threading.Tasks.Task<GrupoComponente.Servicio.Models.ViewModels.UsersIndexViewModel[]> getUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/getUserById", ReplyAction="http://tempuri.org/IUsers/getUserByIdResponse")]
        GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel getUserById(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/getUserById", ReplyAction="http://tempuri.org/IUsers/getUserByIdResponse")]
        System.Threading.Tasks.Task<GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel> getUserByIdAsync(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateUser", ReplyAction="http://tempuri.org/IUsers/CreateUserResponse")]
        string CreateUser(GrupoComponente.Servicio.Models.BindingModels.UsersCreateBindingModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/CreateUser", ReplyAction="http://tempuri.org/IUsers/CreateUserResponse")]
        System.Threading.Tasks.Task<string> CreateUserAsync(GrupoComponente.Servicio.Models.BindingModels.UsersCreateBindingModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/EditUser", ReplyAction="http://tempuri.org/IUsers/EditUserResponse")]
        string EditUser(GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/EditUser", ReplyAction="http://tempuri.org/IUsers/EditUserResponse")]
        System.Threading.Tasks.Task<string> EditUserAsync(GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/DeleteUser", ReplyAction="http://tempuri.org/IUsers/DeleteUserResponse")]
        string DeleteUser(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsers/DeleteUser", ReplyAction="http://tempuri.org/IUsers/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersChannel : GrupoComponente.ServiceReferenceUsers.IUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersClient : System.ServiceModel.ClientBase<GrupoComponente.ServiceReferenceUsers.IUsers>, GrupoComponente.ServiceReferenceUsers.IUsers {
        
        public UsersClient() {
        }
        
        public UsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GrupoComponente.Servicio.Models.ViewModels.UsersIndexViewModel[] getUsers() {
            return base.Channel.getUsers();
        }
        
        public System.Threading.Tasks.Task<GrupoComponente.Servicio.Models.ViewModels.UsersIndexViewModel[]> getUsersAsync() {
            return base.Channel.getUsersAsync();
        }
        
        public GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel getUserById(System.Nullable<int> id) {
            return base.Channel.getUserById(id);
        }
        
        public System.Threading.Tasks.Task<GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel> getUserByIdAsync(System.Nullable<int> id) {
            return base.Channel.getUserByIdAsync(id);
        }
        
        public string CreateUser(GrupoComponente.Servicio.Models.BindingModels.UsersCreateBindingModel model) {
            return base.Channel.CreateUser(model);
        }
        
        public System.Threading.Tasks.Task<string> CreateUserAsync(GrupoComponente.Servicio.Models.BindingModels.UsersCreateBindingModel model) {
            return base.Channel.CreateUserAsync(model);
        }
        
        public string EditUser(GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel model) {
            return base.Channel.EditUser(model);
        }
        
        public System.Threading.Tasks.Task<string> EditUserAsync(GrupoComponente.Servicio.Models.BindingModels.UsersEditBindingModel model) {
            return base.Channel.EditUserAsync(model);
        }
        
        public string DeleteUser(System.Nullable<int> id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(System.Nullable<int> id) {
            return base.Channel.DeleteUserAsync(id);
        }
    }
}
